version = 1

test_patterns = [
  "tests/**"
]

exclude_patterns = [
  "dev/**",
  "docs/**",
  "scripts/**"
]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "docker"
enabled = true